name: 'Get & cache dependencies'
description: 'description :)'
inputs:
    caching:
        description: 'Cache or not'
        required: false
        default: 'true'
        type: boolean
runs:
    using: 'composite' # !!!
    steps:
        - name: Cache dependencies
          if: inputs.caching == 'true'
          id: cache
          uses: actions/cache@v3
          with:
            path: node_modules
            key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        - name: Install dependencies
          if: steps.cache.outputs.cache-hit != 'true'
          run: npm ci
          shell: bash # !!!
